services:
  - type: web
    name: voice-controlled-form-editor
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # You'll set this manually
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: LLAMAPARSE_API_KEY
        sync: false
      - key: PORT
        value: 5000